// Constants for saved legacy runs; current V2 classes live in engine/stats.js.
const LUCKY_BREAK_LOG = "🍀 Lucky Break! Bạn tránh được hậu quả.";

const CLASSES = Object.freeze({
  amazon: {
    name: "Amazon",
    emoji: "🏹",
    hp: 100,
    damageMin: 16,
    damageMax: 23,
    defense: 5,
    accuracy: 92,
    evasion: 14,
    critChance: 0.14,
    resistance: 5,
    energy: 3,
    skill: "Barrage",
  },
  barbarian: {
    name: "Barbarian",
    emoji: "🪓",
    hp: 120,
    damageMin: 15,
    damageMax: 21,
    defense: 8,
    accuracy: 80,
    evasion: 8,
    critChance: 0.1,
    resistance: 5,
    energy: 3,
    skill: "Iron Will",
  },
  assassin: {
    name: "Assassin",
    emoji: "🗡️",
    hp: 95,
    damageMin: 14,
    damageMax: 20,
    defense: 5,
    accuracy: 90,
    evasion: 18,
    critChance: 0.18,
    resistance: 5,
    energy: 3,
    skill: "Shadow Step",
  },
  sorceress: {
    name: "Sorceress",
    emoji: "🔮",
    hp: 100,
    damageMin: 18,
    damageMax: 25,
    defense: 5,
    accuracy: 85,
    evasion: 12,
    critChance: 0.12,
    resistance: 15,
    energy: 4,
    skill: "Arcane Burst",
  },
  druid: {
    name: "Druid",
    emoji: "🌿",
    hp: 110,
    damageMin: 15,
    damageMax: 22,
    defense: 7,
    accuracy: 82,
    evasion: 10,
    critChance: 0.1,
    resistance: 10,
    energy: 3,
    skill: "Wild Regeneration",
  },
  necromancer: {
    name: "Necromancer",
    emoji: "💀",
    hp: 100,
    damageMin: 15,
    damageMax: 21,
    defense: 6,
    accuracy: 84,
    evasion: 10,
    critChance: 0.1,
    resistance: 12,
    energy: 4,
    skill: "Totem Ward",
  },
  paladin: {
    name: "Paladin",
    emoji: "🛡️",
    hp: 115,
    damageMin: 15,
    damageMax: 22,
    defense: 9,
    accuracy: 84,
    evasion: 7,
    critChance: 0.09,
    resistance: 15,
    energy: 3,
    skill: "Divine Shield",
  },
});

const ENEMY_NAMES = [
  "Cave Rat",
  "Wild Boar",
  "Moon Panther",
  "Steel Drone",
  "Dark Cultist",
  "Lost Soul",
  "Storm Shaman",
  "Stone Golem",
  "Void Spawn",
  "Annihilator",
];

const BOSS_NAMES = [
  "The Butcher",
  "Ascendant Riftwalker",
  "Assur",
  "Lucion",
  "Deimoss the Fleshweaver",
];

const FALLBACK_ITEMS = Object.freeze({
  common: [
    { name: "Rusted Edge", attack: 2, text: "+2 ATK" },
    { name: "Dented Plate", defense: 2, text: "+2 DEF" },
    { name: "Red Potion Belt", potions: 1, text: "+1 bình máu" },
    { name: "Rabbit Foot", luck: 1, text: "+1 LUCK" },
  ],
  rare: [
    {
      name: "Hunter’s Fang",
      attack: 4,
      critChance: 0.04,
      text: "+4 ATK, +4% Crit",
    },
    {
      name: "Runed Carapace",
      defense: 5,
      resistance: 5,
      text: "+5 DEF, +5 RES",
    },
    {
      name: "Heart of the Wild",
      maxHp: 22,
      heal: 22,
      text: "+22 HP tối đa và hiện tại",
    },
    { name: "Lucky Coin", luck: 3, text: "+3 LUCK" },
  ],
  legendary: [
    {
      name: "One More Hit",
      escapeTokens: 1,
      maxHp: 15,
      heal: 15,
      text: "+15 HP, nhận 1 Vé thoát",
    },
    {
      name: "The Last Bad Decision",
      attack: 9,
      critChance: 0.08,
      maxHp: -15,
      text: "+9 ATK, +8% Crit, −15 HP tối đa",
    },
    {
      name: "Warden’s Bulwark",
      defense: 10,
      resistance: 12,
      text: "+10 DEF, +12 RES",
    },
    {
      name: "Eye of RNGesus",
      luck: 7,
      attack: 3,
      text: "+7 LUCK, +3 ATK",
    },
  ],
  cursed: [
    {
      name: "Glass Cannon",
      attack: 14,
      defenseSet: 0,
      bonusPenalty: 0.15,
      text: "+14 ATK, DEF về 0, payout −15%",
    },
    {
      name: "Schrödinger’s Armor",
      defense: 12,
      maxHp: -20,
      bonusPenalty: 0.15,
      text: "+12 DEF, −20 HP tối đa, payout −15%",
    },
    {
      name: "Goblin’s Debt",
      luck: 10,
      bonusPenalty: 0.15,
      text: "+10 LUCK, mất 15% payout hiện tại",
    },
  ],
});

const ITEM_LIMITS = Object.freeze({
  defense: [0, Infinity],
  accuracy: [0, Infinity],
  evasion: [0, Infinity],
  luck: [0, Infinity],
  maxHp: [20, Infinity],
  maxEnergy: [1, Infinity],
  resistance: [-50, 75],
  critChance: [0, 0.75],
  potionPower: [-0.3, 0.5],
  bossDamage: [0, 1],
  eliteDamage: [0, 1],
  mimicDetection: [0, 0.5],
  goblinChance: [0, 0.3],
  legendaryFind: [0, 0.25],
  floorHpLoss: [0, 0.2],
  mimicChance: [0, 0.3],
  damageTaken: [0, 0.5],
});

const DISPLAY_STATS = [
  "hp",
  "maxHp",
  "damageMin",
  "damageMax",
  "defense",
  "energy",
  "potions",
  "luck",
  "critChance",
  "evasion",
  "resistance",
  "escapeTokens",
  "accuracy",
  "maxEnergy",
  "potionPower",
  "bossDamage",
  "eliteDamage",
  "mimicDetection",
  "goblinChance",
  "legendaryFind",
  "floorHpLoss",
  "mimicChance",
  "damageTaken",
];
module.exports = {
  LUCKY_BREAK_LOG,
  CLASSES,
  ENEMY_NAMES,
  BOSS_NAMES,
  FALLBACK_ITEMS,
  ITEM_LIMITS,
  DISPLAY_STATS,
};
