const { SlashCommandBuilder, EmbedBuilder, MessageFlags } = require('discord.js');
const RULES = {
  baucua: ['Bầu cua', 'Chọn linh vật trước khi khóa cược. Xuất hiện 1/2/3 lần trả tổng cộng x2/x3/x4. Vật phẩm không có tác dụng trong ván nhiều người. Cược dưới 1.000 xu không nhận EXP, nhiệm vụ hay thưởng phụ; thưởng phụ chỉ rơi xu.'],
  taixiu: ['Tài xỉu', 'Tài 11–17, Xỉu 4–10; bộ ba làm Tài/Xỉu và Chẵn/Lẻ thua. Mỗi người chỉ chọn một cửa trong một ván, có thể cộng thêm cược cùng cửa. Vật phẩm không có tác dụng trong ván nhiều người. Cược dưới 1.000 xu không nhận EXP, nhiệm vụ hay thưởng phụ; thưởng phụ chỉ rơi xu.'],
  chinchiro: ['Chinchiro', 'Nhà cái lắc trước. Khi thắng bằng điểm thường, lãi 80% cược; Shigoro lãi x1, Bão x2, Pin-Zoro x3. Hifumi 1-2-3 mất cược và bị phạt thêm x1. Bot giữ trước một khoản ký quỹ bằng tiền cược để bảo đảm phạt Hifumi, rồi hoàn lại khi không bị phạt. Mỗi ván mới cách nhau 30 giây, kể cả bấm Chơi lại.'],
  oantuti: ['Oẳn tù tì', 'Búa thắng Kéo, Kéo thắng Bao, Bao thắng Búa. Thắng nhận x2, hòa hoàn cược.'],
  blackjack: ['Xì dách', 'Chọn `chedochoi`: **nhà cái bot** (chơi một mình, có gấp đôi và tách bài; thắng thường nhận 2× cược) hoặc **người chơi khác**. **Mọi chế độ:** chỉ được **Dừng khi có ít nhất 16 điểm** (nút Dừng bị khóa nếu dưới 16); khi quắc mọi nút bị khóa; **cả hai cùng quắc thì hòa** và hoàn cược; Gấp đôi chốt tay sau 1 lá nên không bị ràng buộc 16 điểm. Ở chế độ người chơi: Một người mở bàn làm nhà cái; tối đa 3 người chơi có 30 giây để vào. Nhà cái chọn ante, không quá 25% số dư của mình. Người chơi lần lượt rút hoặc dừng; bài của mỗi người được giữ kín, dùng nút **Xem bài của tôi** để xem và thao tác trong bảng riêng, bài chỉ lộ khi kết thúc; nhà cái rút đến khi có ít nhất 15 điểm. Ngũ linh (đủ 5 lá, không quắc) mạnh hơn Xì dách; nếu cả hai cùng Ngũ linh thì tay có tổng điểm nhỏ hơn thắng. Người quắc thua, nhưng nếu nhà cái cũng quắc thì **hòa** và hoàn ante. Thắng nhận lại 2× ante, hòa nhận lại ante. Người tham gia bị khóa khỏi cược game khác đến khi ván kết thúc.'],
  poker: ['Poker', 'Chọn đấu với hai bot hoặc mời một người chơi. Theo, tố hoặc bỏ; xem bài tẩy bằng nút riêng tư. Main Pot và Side Pot được chia tự động.'],
  duangua: ['Đua ngựa', 'Chọn một trong sáu ngựa. Hệ số khóa khi mở bàn; debuff chỉ lộ sau khi khóa cược.'],
  mines: ['Mines', 'Chọn 2–7 mìn trên bàn 20 ô, mở ô an toàn để tăng hệ số rồi rút. Trúng mìn mất cược; ô sao tăng thêm x1,5. Giáp Chống Nổ chỉ vô hiệu hóa một quả mìn duy nhất trên mỗi bản đồ.'],
  coquay: ['Cò quay Nga', 'Đấu súng với Bot, mỗi bên **3 ❤️**. Cược một lần từ đầu (`/choi coquay cuoc:<xu>`); thắng nhận **x2** tiền cược, gục hoặc bỏ cuộc mất cược. Bạn cầm súng trước.\n\n**🔫 Lượt bắn**\n• **Tự bắn** đạn lép: an toàn và **giữ lượt** (loại bớt đạn lép, tăng cơ hội bắn trúng Bot ở phát sau).\n• **Tự bắn** đạn thật: mất 1 ❤️, súng sang tay Bot.\n• **Bắn Bot**: thật hay lép, bắn xong súng luôn sang tay đối phương.\n\n**🔄 Nạp đạn** — số đạn thật 🔴/lép ⚪ của mỗi đợt được công khai, thứ tự bị xáo trộn; mỗi đợt luôn có ít nhất 1 thật và 1 lép. Hết đạn thì nạp đợt mới, người đang cầm súng giữ lượt.\n• Đợt 1 (Khởi động): 2–3 viên\n• Đợt 2 (Căng thẳng): 4–5 viên\n• Đợt 3 trở đi (Khô máu): 6–8 viên\n\n**🤖 Bot** chỉ biết số đạn còn lại như bạn, không nhìn trộm nòng, tính nước tối ưu và chiến đến giọt máu cuối.\n\n**🧰 Vật phẩm** (từ Gacha, bấm nút trong ván, mỗi loại tối đa 1 lần/ván, chỉ dùng trong lượt của bạn)\n• 🔍 **Kính Lúp Soi Nòng** (SR): lén xem viên đang lên nòng là thật hay lép.\n• 🪖 **Bia Đỡ Đạn** (SR): đỡ 1 sát thương khi Bot bắn đạn thật vào bạn.\n• 🪚 **Cưa Cầm Tay** (SSR): viên kế tiếp nếu là đạn thật gây 2 sát thương (kể cả khi tự bắn).\n• ⛓️ **Còng Số 8** (UR): lần tới súng chuyển sang Bot, Bot mất lượt và súng quay lại tay bạn.\n\nBỏ ván quá 10 phút không thao tác sẽ bị xử thua.'],
  hardcore: ['Sinh tồn', 'Vượt tầng và quyết định lúc rút. Chết mất payout tạm giữ; tầng 100 là mốc hoàn thành.'],
  vuatiengviet: ['Vua tiếng Việt', 'Sắp xếp chữ thành từ đúng và trả lời trực tiếp trong kênh game.'],
};

function survivalRules() {
  const overview = new EmbedBuilder().setColor(0x9B59B6).setTitle('📖 SINH TỒN · CÁCH CHƠI')
    .setDescription('Đánh bại quái và vượt từng tầng để làm payout tạm thời tăng lên. Sau mỗi tình huống, đọc diễn biến rồi chọn một nút. **Rút thưởng** chốt payout hiện tại; nếu chết trước khi rút, payout tạm giữ mất hết.')
    .addFields(
      { name: '🚪 Bắt đầu', value: '`/choi sinhton batdau xu:<tiền cược> nhanvat:<class>`\nCó 7 class: Amazon, Assassin, Barbarian, Druid, Necromancer, Paladin và Sorceress. Cược từ **10–100.000 xu** (còn theo giới hạn cược của server). Tiền cược được giữ ngay khi bắt đầu. Mỗi người chỉ có một run đang diễn ra trong server; cần chơi ở kênh Sinh tồn đã cấu hình.', inline: false },
      { name: '🧙 Chọn nhân vật', value: '**Amazon** — chính xác cao; Barrage bắn hai phát.\n**Assassin** — né và chí mạng cao; Shadow Step né phản công.\n**Barbarian** — HP cao; Iron Will gây sát thương vật lý mạnh.\n**Druid** — cân bằng; Wild Regeneration vừa đánh vừa hồi 12% HP.\n**Necromancer** — nhiều năng lượng; Totem Ward gây magic damage và đỡ phản công.\n**Paladin** — phòng thủ và kháng cao; Divine Shield vừa đánh vừa thủ.\n**Sorceress** — magic damage cao; Arcane Burst gây 2,1× sát thương phép.', inline: false },
      { name: '🔁 Vòng chơi và rút thưởng', value: 'Xử lý sự kiện tầng hiện tại để đi tiếp. Mỗi tầng đã vượt làm payout tăng; số xu trong ô **Payout nếu rút** là số nhận được nếu rút ngay. Sau khi vượt ít nhất một tầng, có thể rút ở hầu hết tình huống (RNGesus không có nút rút). Rút trước tầng đầu tiên là **Bỏ run** và làm mất tiền cược.', inline: false },
      { name: '📈 Mốc tiến trình', value: 'Mỗi 5 tầng có checkpoint, hồi đầy HP, nhận 2 bình và chọn một nâng cấp. Checkpoint mạnh dần theo vùng: trước tầng 100 nhận +6 HP/+1 damage; tầng 100–399 nhận +10/+2; tầng 400–699 nhận +14/+3; từ tầng 700 nhận +30/+6. Mỗi 10 tầng thêm một Rift Modifier cộng dồn. Boss Median XL xuất hiện mỗi 50 tầng; tầng 999 là trận Deimoss cuối bắt buộc. Tầng 100 là mốc hoàn thành chính thức.', inline: false },
      { name: '🗺️ Các vùng', value: '**1–99** Sanctuary · **100–199** Duncraig · **200–299** Fauztinville · **300–399** Teganze · **400–499** Scosglen · **500–699** Dimensional Labyrinth · **700–899** Heroic Rift · **900–999** Dimensional Plane.', inline: false },
    );

  const combat = new EmbedBuilder().setColor(0xE67E22).setTitle('⚔️ SINH TỒN · CÁC NÚT HÀNH ĐỘNG')
    .setDescription('Các nút chỉ áp dụng cho tình huống đang hiển thị. Trong giao tranh, quái phản công sau hành động của bạn, trừ khi bạn hạ nó ngay hoặc né được đòn.')
    .addFields(
      { name: '👹 Khi gặp quái', value: '**Tấn công** — đánh thường; hồi 1 năng lượng, nhưng quái phản công nếu còn sống.\n**Phòng thủ** — hồi 1 năng lượng, nhân đôi Defense, chặn thêm 40% sát thương còn lại và miễn chí mạng trong đòn kế tiếp. Boss hiển thị rõ sát thương Vật lý hoặc Phép để bạn chọn cách chống chịu.\n**Kỹ năng** — tốn 2 năng lượng và dùng hiệu ứng riêng của class.\n**Bình máu** — hồi 35% HP tối đa (ít nhất 20 HP, không vượt tối đa); quái vẫn phản công nếu còn sống.\n**Rút thưởng** — kết thúc run và nhận payout đang hiển thị.', inline: false },
      { name: '📦 Khi gặp hòm', value: '**Kiểm tra** — thử phát hiện Mimic, chỉ dùng được một lần; có thể không nhận ra.\n**Mở hòm** — nhận TU, Runeword, Set hoặc SU thật từ dữ liệu Median XL; bot quy đổi các stat chính thành sức mạnh trong run. Trang bị biến mất khi run kết thúc. Nhặt trùng sẽ tăng Lv. và cộng hiệu ứng thêm một lần.\n**Bán hòm** — bỏ cơ hội mở; cộng thêm 15% tiền cược vào payout, phần thưởng cộng thêm của tầng còn một nửa.\n**Tránh Mimic** — chỉ sáng khi đã phát hiện Mimic; bỏ qua hòm và đi tiếp an toàn.', inline: false },
      { name: '🗿 Shrine và phòng sự kiện', value: '**Chạm Shrine** — hiệu ứng ngẫu nhiên: hồi đầy máu, +3 phòng thủ, −15 HP đổi +4 sát thương, +25% tiền cược vào payout, +7 sát thương đổi −4 phòng thủ, hoặc Shrine giả gây sát thương.\n**Bỏ qua** — không nhận hiệu ứng Shrine, đi tiếp.\n**Đi tiếp / Chấp nhận số phận** — xử lý phòng trống hoặc bẫy: Thu thuế giảm payout 15%; kẻ trộm lấy 1 bình máu; Cổng sai giữ nguyên tầng và tạo sự kiện mới.', inline: false },
      { name: '🎲 Sự kiện bất ngờ', value: '**Thợ rèn** dùng 12% payout hiện tại để tăng 1 cấp cho item được đề nghị. **Tu sĩ** dùng 20% payout để giải nguyền, hoàn tác hiệu ứng phạt và đổi item thành SSR. **Người chữa trị** hồi HP và tặng bình máu miễn phí. **Treasure Goblin** có 60% bị bắt để tăng payout; nếu hụt sẽ mất 10% payout.', inline: false },
      { name: '☠️ Khi gặp RNGesus', value: 'RNGesus không thể bị đánh bại; **Chiến đấu** làm run kết thúc. **Bỏ chạy** có 75% thành công; nếu thất bại và đang có Vé Thoát Hiểm, vé tự kích hoạt làm bảo hiểm. **Hối lộ** để đi tiếp nhưng giảm payout 40%. **Cầu nguyện** có 10% thành công: nhận trang bị SSR trở lên và đi tiếp; thất bại là chết. **Vé** chủ động tiêu thụ một Vé Thoát Hiểm để sống sót và đi tiếp. Ở tình huống này không có nút rút thưởng.', inline: false },
      { name: '🧭 Tra cứu thêm', value: '`/choi sinhton tyle` xem xác suất sự kiện và hòm; `hoso` xem thành tích; `xephang` xem top tầng. Chỉ số và hiệu ứng của nút được ghi trong phần **Diễn biến** sau mỗi lựa chọn.', inline: false },
    );

  return [overview, combat];
}

module.exports = { RULES, data: new SlashCommandBuilder().setName('luat').setDescription('Xem luật ngắn của từng game').addStringOption(option => option.setName('trochoi').setDescription('Trò chơi').setRequired(true).addChoices(...Object.entries(RULES).map(([value, [name]]) => ({ name, value })))), async execute(interaction) {
  const key = interaction.options.getString('trochoi', true);
  if (key === 'hardcore') return interaction.reply({ embeds: survivalRules(), flags: MessageFlags.Ephemeral });
  const [name, text] = RULES[key];
  return interaction.reply({ embeds: [new EmbedBuilder().setColor(0x5865F2).setTitle(`📖 ${name}`).setDescription(text).setFooter({ text: 'Dùng /huongdan để xem hệ thống lệnh' })], flags: MessageFlags.Ephemeral });
} };
