"use strict";
// Public API and explicit composition order. Gameplay/UI rules live in the modules below.
const dependencies = {};
Object.assign(dependencies, require("./dependencies")(dependencies));
Object.assign(dependencies, require("./state")(dependencies));
Object.assign(dependencies, require("./payout")(dependencies));
Object.assign(dependencies, require("./equipment")(dependencies));
Object.assign(dependencies, require("./progression")(dependencies));
Object.assign(dependencies, require("./chests")(dependencies));
Object.assign(dependencies, require("./encounters")(dependencies));
Object.assign(dependencies, require("./shrines")(dependencies));
Object.assign(dependencies, require("./combat")(dependencies));
Object.assign(dependencies, require("./combatPassives")(dependencies));
Object.assign(dependencies, require("./combatPreview")(dependencies));
Object.assign(dependencies, require("./choices")(dependencies));
Object.assign(dependencies, require("./eventActions")(dependencies));
Object.assign(dependencies, require("./memories")(dependencies));
Object.assign(dependencies, require("./actions")(dependencies));
const {
  SHRINE_KINDS,
  SHRINE_TREASURE_WEIGHTS,
  makeShrine,
  ITEM_POOLS,
  CONSUMABLE_ITEMS,
  RELIC_ITEMS,
  RELIC_RULES,
  prepareItemCombat,
  noteEvent,
  ITEMS,
  EVENTS,
  EVENT_NAMES,
  BLOOD_PRICES,
  purifierCost,
  PURIFIER_COST_RATE,
  PURIFIER_EVENT_WEIGHT,
  initialize,
  normalize,
  rngesusFleeChance,
  rngesusPrayerChance,
  rollRngesus,
  reviveAfterDeath,
  payout,
  rawPayout,
  taxCost,
  GOBLIN_REWARDS,
  goblinCatchChance,
  goblinEscapeCost,
  heal,
  healingAmount,
  healEvent,
  hurt,
  receiveItem,
  receiveSnapshot,
  cleanse,
  grind,
  remember,
  completeFloor,
  makeChest,
  chestOdds,
  makeSurprise,
  generateEncounter,
  actions,
  act,
  playerAttack,
  attackManaGain,
  skillManaCost,
  skillHpCost,
  skillDamagePreview,
  attackDamagePreview,
  enemyTurn,
  incomingPreview,
  effectiveResistance,
  physicalRange,
  attackDamage,
  legendaryChance,
  effectStatKeys,
  serviceCost,
} = dependencies;
module.exports = {
  SHRINE_KINDS,
  SHRINE_TREASURE_WEIGHTS,
  makeShrine,
  ITEM_POOLS,
  CONSUMABLE_ITEMS,
  RELIC_ITEMS,
  RELIC_RULES,
  prepareItemCombat,
  noteEvent,
  ITEMS,
  EVENTS,
  EVENT_NAMES,
  BLOOD_PRICES,
  purifierCost,
  PURIFIER_COST_RATE,
  PURIFIER_EVENT_WEIGHT,
  initialize,
  normalize,
  rngesusFleeChance,
  rngesusPrayerChance,
  rollRngesus,
  reviveAfterDeath,
  payout,
  rawPayout,
  taxCost,
  GOBLIN_REWARDS,
  goblinCatchChance,
  goblinEscapeCost,
  heal,
  healingAmount,
  healEvent,
  hurt,
  receiveItem,
  receiveSnapshot,
  cleanse,
  grind,
  remember,
  completeFloor,
  makeChest,
  chestOdds,
  makeSurprise,
  generateEncounter,
  actions,
  act,
  playerAttack,
  attackManaGain,
  skillManaCost,
  skillHpCost,
  skillDamagePreview,
  attackDamagePreview,
  enemyTurn,
  incomingPreview,
  effectiveResistance,
  physicalRange,
  attackDamage,
  legendaryChance,
  effectStatKeys,
  serviceCost,
};
