// Public API and explicit composition order. Gameplay/UI rules live in the modules below.
const dependencies = {};
Object.assign(dependencies, require("./dependencies")(dependencies));
Object.assign(dependencies, require("../legacy/fairness")(dependencies));
Object.assign(dependencies, require("../legacy/enemies")(dependencies));
Object.assign(dependencies, require("../legacy/chests")(dependencies));
Object.assign(dependencies, require("../legacy/encounters")(dependencies));
Object.assign(dependencies, require("../legacy/equipment")(dependencies));
Object.assign(dependencies, require("../legacy/progression")(dependencies));
Object.assign(dependencies, require("./records")(dependencies));
Object.assign(dependencies, require("./state")(dependencies));
Object.assign(dependencies, require("./start")(dependencies));
Object.assign(dependencies, require("./setupFlow")(dependencies));
Object.assign(dependencies, require("./setup")(dependencies));
Object.assign(dependencies, require("./settlement")(dependencies));
Object.assign(dependencies, require("../legacy/combat")(dependencies));
Object.assign(dependencies, require("../legacy/eventActions")(dependencies));
Object.assign(dependencies, require("./actions")(dependencies));
Object.assign(dependencies, require("./render")(dependencies));
Object.assign(dependencies, require("./interactions")(dependencies));
const {
  RELEASE,
  hardcoreV2,
  hardcoreStats,
  CLASSES,
  makeChest,
  chestOdds,
  MIN_BET,
  MAX_BET,
  MAX_PAYOUT,
  MAX_FLOOR,
  COMPLETION_FLOOR,
  applyShrine,
  ITEMS,
  hitChance,
  defenseReduction,
  physicalAfterDefense,
  magicAfterResistance,
  resolvePhysicalAttack,
  enemyScale,
  makeEnemy,
  rngesusChance,
  rollRngesus,
  chaosLabel,
  baseMultiplier,
  potentialPayout,
  generateEncounter,
  makeSurprise,
  makeWrongPortal,
  REGIONS,
  RIFT_MODIFIERS,
  regionForFloor,
  checkpointGrowth,
  chooseRarity,
  legendaryChance,
  completeFloor,
  playerAttack,
  enemyTurn,
  applyItem,
  enemyDamageType,
  serviceCost,
  forgeTarget,
  curseTarget,
  luckyBreakChance,
  goblinCatchChance,
  startHardcore,
  openHardcoreSetup,
  handleHardcoreSetup,
  playHardcore,
  getHardcoreByUser,
  getHardcoreRun,
  setMessageId,
  hardcoreEmbed,
  hardcoreRows,
  forceEndHardcoreSession,
  handleHardcoreButton,
  withHardcoreSession,
  getHardcoreRecord,
  getHardcoreTop,
  cleanupStaleHardcoreSessions,
} = dependencies;
module.exports = {
  RELEASE,
  V2: hardcoreV2,
  V2_CLASSES: hardcoreStats.CLASSES,
  makeChest,
  chestOdds,
  MIN_BET,
  MAX_BET,
  MAX_PAYOUT,
  MAX_FLOOR,
  COMPLETION_FLOOR,
  CLASSES,
  applyShrine,
  ITEMS,
  hitChance,
  defenseReduction,
  physicalAfterDefense,
  magicAfterResistance,
  resolvePhysicalAttack,
  enemyScale,
  makeEnemy,
  rngesusChance,
  rollRngesus,
  chaosLabel,
  baseMultiplier,
  potentialPayout,
  generateEncounter,
  makeSurprise,
  makeWrongPortal,
  REGIONS,
  RIFT_MODIFIERS,
  regionForFloor,
  checkpointGrowth,
  makeChest,
  chooseRarity,
  legendaryChance,
  completeFloor,
  playerAttack,
  enemyTurn,
  applyItem,
  enemyDamageType,
  serviceCost,
  forgeTarget,
  curseTarget,
  luckyBreakChance,
  goblinCatchChance,
  startHardcore,
  openHardcoreSetup,
  handleHardcoreSetup,
  playHardcore,
  getHardcoreByUser,
  getHardcoreRun,
  setMessageId,
  hardcoreEmbed,
  hardcoreRows,
  forceEndHardcoreSession,
  handleHardcoreButton,
  withHardcoreSession,
  getHardcoreRecord,
  getHardcoreTop,
  cleanupStaleHardcoreSessions,
};
