// Public API and explicit composition order. Gameplay/UI rules live in the modules below.
const dependencies = {};
Object.assign(dependencies, require("./dependencies")(dependencies));
Object.assign(dependencies, require("./combat")(dependencies));
Object.assign(dependencies, require("./rewards")(dependencies));
Object.assign(dependencies, require("./events")(dependencies));
Object.assign(dependencies, require("./odds")(dependencies));
const {
  runDiamondReward,
  clamp,
  luckyBreakChance,
  goblinCatchChance,
  GOBLIN_REWARDS,
  goblinRewardRarity,
  goblinEscapeCost,
  hitChance,
  defenseReduction,
  physicalAfterDefense,
  magicAfterResistance,
  enemyScale,
  baseMultiplier,
  potentialPayout,
  REGIONS,
  RIFT_MODIFIERS,
  regionForFloor,
  checkpointGrowth,
  BOSS_MECHANICS,
  enemyDamageType,
  serviceCost,
  forgeTarget,
  curseTarget,
  itemEffects,
  itemCurse,
  classShrineActive,
  payoutReductionCost,
  taxCost,
  SURPRISE_EVENTS,
  CLASS_SHRINE_TEXT,
  MERCHANT_OFFERS,
  surpriseOptions,
  PORTAL_GOOD_CHANCE,
  PORTAL_GOOD_EFFECTS,
  portalBadEffects,
  portalEffectOdds,
  trapOdds,
  SURPRISE_ODDS,
  FIXED_SURPRISES,
  surpriseOdds,
  SHRINE_KINDS,
  SHRINE_EFFECTS,
  shrineFakeDamage,
  shrineOutcomes,
} = dependencies;
module.exports = {
  runDiamondReward,
  clamp,
  luckyBreakChance,
  goblinCatchChance,
  GOBLIN_REWARDS,
  goblinRewardRarity,
  goblinEscapeCost,
  hitChance,
  defenseReduction,
  physicalAfterDefense,
  magicAfterResistance,
  enemyScale,
  baseMultiplier,
  potentialPayout,
  REGIONS,
  RIFT_MODIFIERS,
  regionForFloor,
  checkpointGrowth,
  BOSS_MECHANICS,
  enemyDamageType,
  serviceCost,
  forgeTarget,
  curseTarget,
  itemEffects,
  itemCurse,
  classShrineActive,
  payoutReductionCost,
  taxCost,
  SURPRISE_EVENTS,
  CLASS_SHRINE_TEXT,
  MERCHANT_OFFERS,
  surpriseOptions,
  PORTAL_GOOD_CHANCE,
  PORTAL_GOOD_EFFECTS,
  portalBadEffects,
  portalEffectOdds,
  trapOdds,
  SURPRISE_ODDS,
  FIXED_SURPRISES,
  surpriseOdds,
  SHRINE_KINDS,
  SHRINE_EFFECTS,
  shrineFakeDamage,
  shrineOutcomes,
};
